# 通用的构建参数
x-build-args: &build-args
  # 代理地址，在 Docker 中使用 host.docker.internal 访问主机
  # PROXY: "http://host.docker.internal:7897"
  PROXY: ""
  NO_PROXY: "localhost,127.0.0.1"

  # 使用国内镜像下载 apt
  USE_MIRROR: "no" # or "yes"

  # 额外包安装
  EXTRA_PACKAGES: "vim nano"

# 通用的服务配置
x-common: &common
  volumes:
    - ~/ctf:/ctf # 修改为你的目录
  cap_add:
    - SYS_PTRACE
  security_opt:
    - seccomp=unconfined
  extra_hosts:
    - "host.docker.internal:host-gateway"
  stdin_open: true
  tty: true

services:
  ubuntu24.04:
    build:
      context: .
      args:
        IMAGE: ubuntu:24.04
        <<: *build-args
        PYTHON_VERSION: 3.12.0
        GDB_VERSION: 15.2
        GDB_MULTIARCH: no
        RUBY_VERSION: 3.2.6
    <<: *common
    image: nopwnv2:24.04
    hostname: NoPwnV2_24.04
    container_name: NoPwn2404

  ubuntu22.04:
    build:
      context: .
      args:
        IMAGE: ubuntu:22.04
        <<: *build-args
        PYTHON_VERSION: 3.12.0
        GDB_VERSION: 15.2
        GDB_MULTIARCH: no
        RUBY_VERSION: 3.2.6
    <<: *common
    image: nopwnv2:22.04
    hostname: NoPwnV2_22.04
    container_name: NoPwn2204

  ubuntu20.04:
    build:
      context: .
      args:
        IMAGE: ubuntu:20.04
        <<: *build-args
        PYTHON_VERSION: 3.12.0
        GDB_VERSION: 15.2
        GDB_MULTIARCH: no
        RUBY_VERSION: 3.2.6
    <<: *common
    image: nopwnv2:20.04
    hostname: NoPwnV2_20.04
    container_name: NoPwn2004

  ubuntu18.04:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu1804
      args:
        <<: *build-args
        PYTHON_VERSION: 3.12.0
        GDB_VERSION: 15.2
        GDB_MULTIARCH: no
        RUBY_VERSION: 3.2.6
        CURSES_VERSION: 6.4
    <<: *common
    image: nopwnv2:18.04
    hostname: NoPwnV2_18.04
    container_name: NoPwn1804

  ubuntu16.04:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu1604
      args:
        <<: *build-args
        PYTHON_VERSION: 3.12.0
        GDB_VERSION: 13.2
        GDB_MULTIARCH: no
        RUBY_VERSION: 3.2.6
    <<: *common
    image: nopwnv2:16.04
    hostname: NoPwnV2_16.04
    container_name: NoPwn1604
