# Modified from pastel-powerline(https://starship.rs/presets/pastel-powerline.html)
# Inspired by cattppuccin(https://github.com/catppuccin)
# Modify colors in `[palettes.novative]` to custom

palette = 'novative'

format = """
[\ue0b6](userinfo)\
$os\
$username\
[\ue0b4](fg:userinfo bg:path)\
$directory\
[](fg:path bg:git)\
$git_branch\
$git_status\
[](fg:git bg:language)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:language bg:docker)\
$docker_context\
[](fg:docker bg:time)\
$time\
[ ](fg:time)\
"""

# Disable the blank line at the start of the prompt
add_newline = true

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below

[palettes.novative]
userinfo = '#8AADF4'
white = '#FFFFFF'
text = '#494D64'
path = '#F5BDE6'
git = '#B7BDF8'
language = '#7dc4e4'
docker = '#eebebe'
time = '#c6a0f6'

[username]
show_always = true
style_user = "bg:userinfo fg:text"
style_root = "bg:userinfo fg:text"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:userinfo fg:white"
disabled = false # Disabled by default

[os.symbols]
Windows = "\uE62A "
Linux = "\uF17C "
Ubuntu = "\uF31b "

[directory]
style = "bg:path fg:text"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "..\ue5fe../"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:language fg:text"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:docker"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:language fg:text"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:language fg:text"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:git fg:text"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:git fg:text"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:language fg:text"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:language fg:text"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:language fg:text"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:language fg:text"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:language fg:text"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:language fg:text"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:language fg:text"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:language fg:text"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:time fg:text"
format = '[ ♥ $time ]($style)'
