name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - "24.04"
          - "22.04"
          - "20.04"
          - "18.04"
          - "16.04"
        file:
          - "Dockerfile"
          - "Dockerfile"
          - "Dockerfile"
          - "Dockerfile.ubuntu1804"
          - "Dockerfile.ubuntu1604"
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4

    - name: Build Ubuntu ${{ matrix.version }}
      run: docker build . --file ${{ matrix.file }} --build-arg IMAGE=ubuntu:${{ matrix.version }} --tag nopwnv2:${{ matrix.version }}-$(date +%s)
